In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [2]:
i = 180
# prob_path = f"/raid/zhuxihuan/data/body/expe6/val_data/probs/{i}.npy"
# prob = np.load(prob_path)
# print(prob.shape)
# plt.imshow(prob[:,:,1])# 

In [3]:
# gt_path = f"/raid/zhuxihuan/data/body/expe6/val_data/GT/{i}.npy" 
# gt = np.load(gt_path)
# print(gt)
# plt.imshow(gt)

In [4]:
# compo_path = f"/home/zhuxihuan/code/MetaSeg/expe6/val_measure/components/best-loss-037epoch.bin/components{i}.p"
# compo = pickle.load( open( compo_path, "rb" ) )
# print(compo.shape)
# print(np.unique(compo))
# print(compo)
# #plt.imshow(compo)
# print(np.sum(compo))
# print(512*512)

In [5]:
# metric_path = f"/home/zhuxihuan/code/MetaSeg/expe6/val_measure/metrics/best-loss-037epoch.bin/metrics{i}.p"
# metric = pickle.load( open( metric_path, "rb" ) )
# print(metric)

In [6]:
# probs = np.ones((10,10,2))
# for i in range(probs.shape[0]):
#     if i <= 5:
#         probs[i,:,0] = (i+1)/probs.shape[0]
#     else:
#         probs[i,:,0] = (10-i+1)/probs.shape[0]
#     probs[i,:,1] = 1 - probs[i,:,0]
# print(probs[:,:,1])

In [7]:
# print(probs[:,:,1]>=0.5)

In [8]:
gt = np.ones((10,10))
print(gt)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [9]:
metric = {'iou': [0.5714285714285714, 0.0, 0.5], 'iou0': [0, 1, 0], 'class': [1, 0, 1],
 'E': [0.7607909291982651, 0.9903165102005005, 0.8580561478932699], 
 'E_in': [0.6907378236452738, 0.9709502458572388, 0.8016090989112854],
 'E_bd': [0.9709502458572388, 0.9999996423721313, 0.9709502458572388],
 'E_rel': [3.0431637167930603, 1.4854747653007507, 2.5741684436798096],
 'E_rel_in': [2.0722134709358215, 0.4854751229286194, 1.6032181978225708],
 'D': [0.4999999925494194, 0.9333333174387614, 0.5999999841054281], 
 'D_in': [0.4000000059604645, 0.7999999523162842, 0.5],
 'D_bd': [0.7999999523162842, 1.0, 0.7999999523162842], 
 'D_rel': [1.9999999701976776, 1.399999976158142, 1.7999999523162842],
 'D_rel_in': [1.2000000178813934, 0.3999999761581421, 1.0], 
 'S': [40, 30, 30], 'S_in': [30, 10, 20], 'S_bd': [10, 20, 10], 'S_rel': [4.0, 1.5, 3.0], 'S_rel_in': [3.0, 0.5, 2.0],
 'cprob0': [0.25000000558793545, 0.5333333412806193, 0.30000000695387524],
 'cprob1': [0.75, 0.46666666865348816, 0.700000007947286]}
print(metric)

{'iou': [0.5714285714285714, 0.0, 0.5], 'iou0': [0, 1, 0], 'class': [1, 0, 1], 'E': [0.7607909291982651, 0.9903165102005005, 0.8580561478932699], 'E_in': [0.6907378236452738, 0.9709502458572388, 0.8016090989112854], 'E_bd': [0.9709502458572388, 0.9999996423721313, 0.9709502458572388], 'E_rel': [3.0431637167930603, 1.4854747653007507, 2.5741684436798096], 'E_rel_in': [2.0722134709358215, 0.4854751229286194, 1.6032181978225708], 'D': [0.4999999925494194, 0.9333333174387614, 0.5999999841054281], 'D_in': [0.4000000059604645, 0.7999999523162842, 0.5], 'D_bd': [0.7999999523162842, 1.0, 0.7999999523162842], 'D_rel': [1.9999999701976776, 1.399999976158142, 1.7999999523162842], 'D_rel_in': [1.2000000178813934, 0.3999999761581421, 1.0], 'S': [40, 30, 30], 'S_in': [30, 10, 20], 'S_bd': [10, 20, 10], 'S_rel': [4.0, 1.5, 3.0], 'S_rel_in': [3.0, 0.5, 2.0], 'cprob0': [0.25000000558793545, 0.5333333412806193, 0.30000000695387524], 'cprob1': [0.75, 0.46666666865348816, 0.700000007947286]}


In [10]:
component = [[ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
             [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
             [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
             [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
             [-2,-2,-2,-2,-2,-2,-2,-2,-2,-2],
             [ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
             [-2,-2,-2,-2,-2,-2,-2,-2,-2,-2],
             [-3,-3,-3,-3,-3,-3,-3,-3,-3,-3],
             [ 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
             [ 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]
print(component)

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1], [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2], [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3], [3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]


In [11]:
#metric
"""
{'iou': [0.5714285714285714, 0.0, 0.5], 'iou0': [0, 1, 0], 'class': [1, 0, 1],
 'E': [0.7607909291982651, 0.9903165102005005, 0.8580561478932699], 
 'E_in': [0.6907378236452738, 0.9709502458572388, 0.8016090989112854],
 'E_bd': [0.9709502458572388, 0.9999996423721313, 0.9709502458572388],
 'E_rel': [3.0431637167930603, 1.4854747653007507, 2.5741684436798096],
 'E_rel_in': [2.0722134709358215, 0.4854751229286194, 1.6032181978225708],
 'D': [0.4999999925494194, 0.9333333174387614, 0.5999999841054281], 
 'D_in': [0.4000000059604645, 0.7999999523162842, 0.5],
 'D_bd': [0.7999999523162842, 1.0, 0.7999999523162842], 
 'D_rel': [1.9999999701976776, 1.399999976158142, 1.7999999523162842],
 'D_rel_in': [1.2000000178813934, 0.3999999761581421, 1.0], 
 'S': [40, 30, 30], 'S_in': [30, 10, 20], 'S_bd': [10, 20, 10], 'S_rel': [4.0, 1.5, 3.0], 'S_rel_in': [3.0, 0.5, 2.0],
 'cprob0': [0.25000000558793545, 0.5333333412806193, 0.30000000695387524],
 'cprob1': [0.75, 0.46666666865348816, 0.700000007947286]}
 """
#component
"""
[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [ 2  2  2  2  2  2  2  2  2  2]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-3 -3 -3 -3 -3 -3 -3 -3 -3 -3]
 [ 3  3  3  3  3  3  3  3  3  3]
 [ 3  3  3  3  3  3  3  3  3  3]]
 """
#prob
"""
[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [False False False False False False False False False False]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]
"""

'\n[[ True  True  True  True  True  True  True  True  True  True]\n [ True  True  True  True  True  True  True  True  True  True]\n [ True  True  True  True  True  True  True  True  True  True]\n [ True  True  True  True  True  True  True  True  True  True]\n [ True  True  True  True  True  True  True  True  True  True]\n [False False False False False False False False False False]\n [ True  True  True  True  True  True  True  True  True  True]\n [ True  True  True  True  True  True  True  True  True  True]\n [ True  True  True  True  True  True  True  True  True  True]\n [ True  True  True  True  True  True  True  True  True  True]]\n'

In [12]:
def entropy( probs ):

    E = np.sum( np.multiply( probs, np.log(probs+np.finfo(np.float32).eps) ) , axis=-1) / np.log(1.0/probs.shape[-1])
    return np.asarray( E, dtype="float32" )

def probdist( probs ):
    arrayA = np.asarray(np.argsort(probs,axis=-1), dtype="uint8")
    arrayD = np.ones( probs.shape[:-1], dtype="float32" )

    P = probs
    D = arrayD
    A = arrayA

    for i in range( arrayD.shape[0] ):
        for j in range( arrayD.shape[1] ):
            D[i,j] = ( 1 - P[ i, j, A[i,j,-1] ] + P[ i, j, A[i,j,-2] ] )

    return arrayD

def prediction(probs, gt, ignore=True ):
    pred = np.asarray( np.argmax( probs, axis=-1 ), dtype="uint8" )
    if ignore == True:
        pred[ gt==255 ] = 255
    return pred

In [13]:
ii = 180
prob_path = f"/raid/zhuxihuan/data/body/expe6/val_data/probs/{ii}.npy"
probs = np.load(prob_path)
print(probs.shape)
gt_path = f"/raid/zhuxihuan/data/body/expe6/val_data/GT/{ii}.npy" 
gt = np.load(gt_path)
print(gt.shape)
compo_path = f"/home/zhuxihuan/code/MetaSeg/expe6/val_measure/components/best-loss-037epoch.bin/components{ii}.p"
compo = pickle.load( open( compo_path, "rb" ) )
print(compo.shape)
seg = np.asarray( prediction(probs, gt, ignore=True ), dtype="uint8" )
print(seg.shape)


(512, 512, 2)
(512, 512)
(512, 512)
(512, 512)


In [14]:
print(compo[240:256, 128:144])

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1]
 [ 1  1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1]
 [ 1  1  1  1  1  1 -1 -1 -1 -1 -2 -2 -2 -2 -2 -2]
 [ 1  1  1  1  1 -1 -1 -2 -2 -2 -2  2  2  2  2  2]
 [ 1  1  1 -1 -1 -1 -2 -2  2  2  2  2  2  2  2  2]
 [ 1  1 -1 -1 -2 -2 -2  2  2  2  2  2  2  2  2  2]
 [ 1 -1 -1 -2 -2  2  2  2  2  2  2  2  2  2  2  2]
 [-1 -1 -2 -2  2  2  2  2  2  2  2  2  2  2  2  2]
 [-1 -2 -2  2  2  2  2  2  2  2  2  2  2  2  2  2]]


In [15]:
def computeMetrics(gt, probs, seg, compo):
    flag = np.zeros( (gt.shape[0], gt.shape[1]), dtype="uint8" )
    print(flag.shape)
    marked = np.zeros( (gt.shape[0], gt.shape[1]), dtype="uint8" )
    print(marked.shape)
    #E:每个像素点的交叉熵(10,10)， D:probability margin(10, 10)
    heatmaps = { "E": entropy( probs ), "D": probdist( probs )}  
    #print(heatmaps['E'].shape, heatmaps['D'].shape)

    metrics = { "iou": list([]), "iou0": list([]), "class": list([]) } #, "mean_x": list([]), "mean_y": list([]) }

    #E和D和S的五种值，原始，in， bd， 相关， 相关in
    for m in list(heatmaps)+["S"]:
        metrics[m          ] = list([])
        metrics[m+"_in"    ] = list([])
        metrics[m+"_bd"    ] = list([])
        metrics[m+"_rel"   ] = list([])
        metrics[m+"_rel_in"] = list([])

    nclasses  = probs.shape[-1]
    #每个像素点的类别的拆分  
    for i in range(nclasses):
        metrics['cprob'+str(i)] = list([])
    print(metrics)
    step = 8
    block = 0
    for i in range(0, probs.shape[0], step):
        for j in range(0, probs.shape[1], step):
    #         if flag[i, j] == 1:
    #             continue
            ssum = 0
            new_ii, new_jj = i, j
            while ssum <  step * step:
                for m in metrics:
                    metrics[m].append( 0 )
                #print(ssum)
                new_i, new_j = new_ii, new_jj
                #print(new_i, new_j)
                I, U = 0, 0 
                c = seg[new_i, new_j]
                block = block + 1
                ind = abs(compo[new_i, new_j])
                n_in, n_bd = 0, 0
                first = True
                #print(i + step,probs.shape[0], min(i + step, probs.shape[0]))
                for x in range(new_i, min(i + step, probs.shape[0])):
                    for  y in range(j, min(j + step, probs.shape[1])):
                        if flag[x, y] == 1:
                            continue
                        #print(x , y)
                        # compute all metrics
                        #print("in compute:n_in, n_bd", n_in, "^^^^^", n_bd)
                        if compo[x, y] in [ind, -ind]:
                            flag[x, y] = 1
                            ssum += 1
                            marked[x, y] = block
                            if compo[x,y] == ind:
                                for h in heatmaps:
        #                             print(heatmaps[h][x,y])
        #                             print(metrics[h+"_in"][-1])
                                    metrics[h+"_in"][-1] += heatmaps[h][x,y]
                                n_in += 1
                            elif compo[x,y] == -ind:
                                for h in heatmaps:
                                    metrics[h+"_bd"][-1] += heatmaps[h][x,y]
                                n_bd += 1
                            for ic in range(nclasses):
                                metrics["cprob"+str(ic)][-1] += probs[x,y,ic]

                            if gt != []:
                                if gt[x,y] == c:
                                    I += 1
                            U += 1
                        elif first:
                            new_ii = x
                            new_jj = y
                            first = False

                        metrics["class"   ][-1] = c
                        if gt != []:
                            metrics["iou"     ][-1] = float(I) / (float(U))
                            metrics["iou0"    ][-1] = int(I == 0)
                        else:
                            metrics["iou"     ][-1] = -1
                            metrics["iou0"    ][-1] = -1
                        metrics["S"       ][-1] = n_in + n_bd
                        metrics["S_in"    ][-1] = n_in
                        metrics["S_bd"    ][-1] = n_bd
                        if n_bd > 0:
                            metrics["S_rel"   ][-1] = float( n_in + n_bd ) / (float(n_bd))
                            metrics["S_rel_in"][-1] = float( n_in ) / (float(n_bd))
                        else:
                            metrics["S_rel"   ][-1] = float( n_in + n_bd ) / (float(n_bd) + step * 4)
                            metrics["S_rel_in"][-1] = float( n_in ) / (float(n_bd) + step * 4)
                        #metrics["mean_x"][-1] /= ( n_in + n_bd )
                        #metrics["mean_y"][-1] /= ( n_in + n_bd )

                        for nc in range(nclasses):
                            metrics["cprob"+str(nc)][-1] /= ( n_in + n_bd )

                        for h in heatmaps:
                            metrics[h          ][-1] = (metrics[h+"_in"][-1] + metrics[h+"_bd"][-1]) / (float( n_in + n_bd ))
                            if ( n_in > 0 ):
                                metrics[      h+"_in"][-1] /= (float(n_in))
                            if n_bd > 0:
                                metrics[h+"_bd"    ][-1] /= (float(n_bd))

                            metrics[h+"_rel"   ][-1] = metrics[h      ][-1] * metrics["S_rel"   ][-1]
                            metrics[h+"_rel_in"][-1] = metrics[h+"_in"][-1] * metrics["S_rel_in"][-1]
    return marked, metrics, block
    # print(marked[240:256, 128:144])
    # print(block)
    #     print(metrics)

In [16]:
marked, metrics, block = computeMetrics(gt, probs, seg, compo)
print(metrics)

(512, 512)
(512, 512)
{'iou': [], 'iou0': [], 'class': [], 'E': [], 'E_in': [], 'E_bd': [], 'E_rel': [], 'E_rel_in': [], 'D': [], 'D_in': [], 'D_bd': [], 'D_rel': [], 'D_rel_in': [], 'S': [], 'S_in': [], 'S_bd': [], 'S_rel': [], 'S_rel_in': [], 'cprob0': [], 'cprob1': []}


/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:70: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:80: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


{'iou': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1